---
  language: python
  services: docker

  env:
    global:
      - ROLE_NAME: certbot
    matrix:
      - MOLECULE_DISTRO: centos:8
      - MOLECULE_DISTRO: centos:7
      - MOLECULE_DISTRO: centos:6
      - MOLECULE_DISTRO: ubuntu:bionic
      - MOLECULE_DISTRO: ubuntu:xenial
      - MOLECULE_DISTRO: debian:10

  install:
    # Install test dependencies.
    - pip install molecule docker

  script:
    # Run tests.
    - molecule test
