---

- set_fact:
    _zeus_config_failed: false

- name: "prepare ~> checking configuration"
  include_tasks: "verify-config.yml"

- name: "prepare ~> installing packages"
  include_tasks: "install.yml"