---
# tasks file for certbot
- import_tasks: install-certbot.yml

- name: Set certbot script
  set_fact:
    certbot_script: certbot certonly

- name: Set certbot script on staging environment
  set_fact:
    certbot_command_options: "{{ certbot_command_options + [ '--staging' ] + [ '--dry-run' ] }}"
  when: certbot_staging

- name: Load dns plugin
  include: "plugins/{{ certbot_dns_plugin }}.yml"
  when: certbot_use_plugin

- name: Install certbot dns plugin
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ certbot_dns_plugin_package }}"
  when: certbot_use_plugin

- name: Debug certbot command options
  debug: var=certbot_command_options

- import_tasks: create-cert.yml
