- name: ensure profile.d path exists
  file:
    path: /etc/profile.d
    state: directory

- name: configures proxy
  template:
    src: olympus_proxy.sh.j2
    dest: /etc/profile.d/olympus_proxy.sh
  when: olympus_proxy is defined and olympus_proxy is string