---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
- name: instance
  image: "kilip/molecule-${MOLECULE_DISTRO:-centos:7}"
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  privileged: true
  pre_build_image: true
  #volumes:
  #- /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  config_options:
    defaults:
      interpreter_python: auto_silent

verifier:
  name: testinfra
  lint:
    name: flake8
