---
name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
jobs:
  molecule:
    name: Molecule (Python-${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule
          make install-role
      - name: run tests
        run: |
          molecule test
